name: CI

on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.64.0"

      - name: Build
        run: hugo 

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: anaschwendler/anaschwendler.github.io
          publish_dir: ./public
          user_name: anaschwendler
          user_email: ${{ secrets.EMAIL }}
          publish_branch: main
          cname: ${{ secrets.CNAME }}